---
title: "Twitter Feed"
type: "exercise"
description: "Render a static Twitter feed with React stateless components"
tags: "javascript, react, stateless components"
ignore:
- "node_modules/"
- "twitter-feed.md"
